import type { Product } from "@/types/product";

/**
 * Fixture de produtos — uso restrito a testes (vitest) e scripts de seed.
 * Fonte de verdade em runtime: tabela `public.products` no Supabase.
 *
 * NÃO importar deste arquivo a partir de `src/app/`, `src/components/`,
 * `src/server/` ou `src/stores/` — produção lê do banco.
 */
export const productFixtures: readonly Product[] = [
  {
    id: "1",
    slug: "bolo-no-pote-brigadeiro",
    name: "Bolo no Pote — Brigadeiro",
    description:
      "Massa úmida de chocolate em camadas intercaladas com brigadeiro feito de leite condensado de castanha de caju. Sem lactose, sem ovo. Vem em pote individual pronto para comer — sem precisar de talher.",
    category: "bolo-no-pote",
    gramatura_g: 230,
    price_site: 17.9,
    price_ifood: 23.3,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos", "afetivos"],
    photo: {
      url: "/produtos/brownie-pote.png",
      alt: "Bolo no pote de brigadeiro com logo Vegana ao fundo",
    },
    photoSecondary: {
      url: "/produtos/bolo-cenoura-brigadeiro-2.png",
      alt: "Close do recheio cremoso de brigadeiro",
    },
    active: true,
    stock: 14,
    lowStockThreshold: 3,
    ifoodRating: 4.9,
    ifoodOrderCount: 340,
    serves: 1,
    contains: ["castanha-de-caju", "cacau"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "2",
    slug: "bolo-no-pote-prestigio",
    name: "Bolo no Pote — Prestígio",
    description:
      "Massa de chocolate, camadas de coco cremoso e brigadeiro de castanha de caju. A combinação clássica de chocolate com coco em versão vegana e sem lactose.",
    category: "bolo-no-pote",
    gramatura_g: 230,
    price_site: 17.9,
    price_ifood: 23.3,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos"],
    photo: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Bolo no pote de prestígio — chocolate e coco",
    },
    photoSecondary: {
      url: "/produtos/brownie-pote.png",
      alt: "Corte mostrando camadas de chocolate e coco",
    },
    active: true,
    stock: 8,
    lowStockThreshold: 3,
    ifoodRating: 4.9,
    ifoodOrderCount: 310,
    serves: 1,
    contains: ["castanha-de-caju", "coco", "cacau"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "3",
    slug: "bolo-cenoura-cobertura",
    name: "Bolo de Cenoura com Brigadeiro",
    description:
      "Massa úmida de cenoura com cobertura brilhante de brigadeiro de cacau. Feito com leite de coco, sem lactose, sem ovo. O clássico que todo mundo ama — agora sem comprometer ninguém à mesa.",
    category: "bolo",
    gramatura_g: 170,
    price_site: 11.9,
    price_ifood: 15.5,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos", "afetivos"],
    photo: {
      url: "/produtos/bolo-cenoura-brigadeiro.png",
      alt: "Bolo de cenoura com cobertura de brigadeiro em prato claro sobre madeira",
    },
    photoSecondary: {
      url: "/produtos/bolo-cenoura-calda.png",
      alt: "Fatia cortada revelando massa úmida",
    },
    active: true,
    stock: 2,
    lowStockThreshold: 3,
    ifoodRating: 4.8,
    ifoodOrderCount: 180,
    serves: 8,
    contains: ["castanha-de-caju", "cacau"],
    freezable: true,
    availableForPreorder: false,
  },
  {
    id: "4",
    slug: "brownie-chocolate",
    name: "Brownie de Chocolate",
    description:
      "Denso, úmido, com casca crocante e recheio cremoso de brigadeiro de cacau entre as camadas. Cacau 70%, sem lactose, sem ovo. Vem em pack com 3 unidades.",
    category: "bolo",
    gramatura_g: 90,
    price_site: 18.9,
    price_ifood: 24.6,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos", "presente"],
    photo: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Stack de brownies de chocolate com recheio de brigadeiro em prato branco",
    },
    photoSecondary: {
      url: "/produtos/brownie-pote.png",
      alt: "Brownie cortado mostrando recheio cremoso",
    },
    active: true,
    stock: 20,
    lowStockThreshold: 5,
    ifoodRating: 4.8,
    ifoodOrderCount: 145,
    serves: 3,
    contains: ["castanha-de-caju", "cacau"],
    freezable: true,
    availableForPreorder: false,
  },
  {
    id: "5",
    slug: "bombom-brigadeiro",
    name: "Bombom de Brigadeiro",
    description:
      "Recheio cremoso de brigadeiro de castanha de caju envolvido em chocolate meio amargo. Sem lactose, sem ovo. Ideal para presentear ou fechar a refeição com algo especial.",
    category: "docinho",
    gramatura_g: 20,
    price_site: 7,
    price_ifood: 9.1,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos", "presente"],
    photo: {
      url: "/produtos/bombom-coco.png",
      alt: "Bombom cortado ao meio mostrando recheio cremoso de brigadeiro",
    },
    photoSecondary: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Bombons em caixa de presente",
    },
    active: true,
    stock: 0,
    lowStockThreshold: 5,
    ifoodRating: 4.9,
    ifoodOrderCount: 95,
    serves: 1,
    contains: ["castanha-de-caju", "cacau"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "6",
    slug: "bolo-no-pote-ninho-morango",
    name: "Bolo no Pote — Ninho com Morango",
    description:
      "Massa branca, creme à base de leite de coco e castanha de caju, morangos frescos em camadas. Leve, refrescante e bonito — favorito da Paula para servir à mesa.",
    category: "bolo-no-pote",
    gramatura_g: 230,
    price_site: 19.9,
    price_ifood: 25.9,
    attributes: ["sem-lactose", "vegano"],
    tags: ["novidades", "presente"],
    photo: {
      url: "/produtos/brownie-pote.png",
      alt: "Bolo no pote de leite ninho com morango em pote transparente",
    },
    photoSecondary: {
      url: "/produtos/bolo-baunilha.png",
      alt: "Close do creme e morangos",
    },
    active: true,
    stock: 3,
    lowStockThreshold: 3,
    ifoodRating: 4.9,
    ifoodOrderCount: 230,
    serves: 1,
    contains: ["castanha-de-caju", "coco"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "7",
    slug: "bolo-no-pote-limao",
    name: "Bolo no Pote — Limão Siciliano",
    description:
      "Massa aerada de limão siciliano, creme cítrico de leite de coco, raspas frescas na finalização. Refrescante e elegante — para quem prefere o azedo ao doce.",
    category: "bolo-no-pote",
    gramatura_g: 220,
    price_site: 18.9,
    price_ifood: 24.6,
    attributes: ["sem-lactose", "vegano"],
    tags: ["novidades"],
    photo: {
      url: "/produtos/brownie-pote.png",
      alt: "Bolo no pote de limão siciliano em pote transparente",
    },
    photoSecondary: {
      url: "/produtos/bolo-cenoura-brigadeiro-2.png",
      alt: "Close das raspas de limão",
    },
    active: true,
    stock: 12,
    lowStockThreshold: 3,
    ifoodRating: 4.8,
    ifoodOrderCount: 120,
    serves: 1,
    contains: ["coco"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "8",
    slug: "bolo-formigueiro",
    name: "Bolo Formigueiro",
    description:
      "Massa fofa de baunilha com pedacinhos de chocolate picado, leite de coco e óleo de coco. Clássico da infância em versão vegana — leve, macio, sem lactose.",
    category: "bolo",
    gramatura_g: 180,
    price_site: 12.9,
    price_ifood: 16.8,
    attributes: ["sem-lactose", "vegano"],
    tags: ["novidades", "afetivos"],
    photo: {
      url: "/produtos/bolo-baunilha.png",
      alt: "Fatia de bolo formigueiro em superfície clara",
    },
    photoSecondary: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Corte do bolo formigueiro mostrando chocolate",
    },
    active: true,
    stock: 1,
    lowStockThreshold: 3,
    ifoodRating: 4.7,
    ifoodOrderCount: 85,
    serves: 6,
    contains: ["cacau", "coco"],
    freezable: true,
    availableForPreorder: false,
  },
  {
    id: "9",
    slug: "bolo-chocolate-molhadinho",
    name: "Bolo de Chocolate Molhadinho",
    description:
      "Massa densa e úmida de cacau 70%, calda de chocolate meio amargo que penetra a massa antes de servir. Sem lactose, sem ovo. Para os que levam chocolate a sério.",
    category: "bolo",
    gramatura_g: 200,
    price_site: 14.9,
    price_ifood: 19.4,
    attributes: ["sem-lactose", "vegano"],
    tags: ["afetivos"],
    photo: {
      url: "/produtos/bolo-cenoura-calda.png",
      alt: "Bolo de chocolate com calda em prato claro",
    },
    photoSecondary: {
      url: "/produtos/bolo-cenoura-brigadeiro-2.png",
      alt: "Fatia mostrando calda penetrando a massa",
    },
    active: true,
    stock: 7,
    lowStockThreshold: 3,
    ifoodRating: 4.9,
    ifoodOrderCount: 140,
    serves: 8,
    contains: ["cacau"],
    freezable: true,
    availableForPreorder: false,
  },
  {
    id: "10",
    slug: "beijinho-coco",
    name: "Beijinho de Coco",
    description:
      "Doce cremoso de coco fresco e leite condensado de castanha de caju, coberto com coco ralado. Sem lactose, sem ovo. Delicado e com sabor genuíno de coco.",
    category: "docinho",
    gramatura_g: 22,
    price_site: 6.5,
    price_ifood: 8.5,
    attributes: ["sem-lactose", "vegano"],
    tags: ["presente", "afetivos"],
    photo: {
      url: "/produtos/bombom-coco.png",
      alt: "Bombom de coco cortado ao meio sobre prato claro",
    },
    photoSecondary: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Bandeja com vários beijinhos",
    },
    active: true,
    stock: 30,
    lowStockThreshold: 5,
    ifoodRating: 4.8,
    ifoodOrderCount: 75,
    serves: 1,
    contains: ["castanha-de-caju", "coco"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "11",
    slug: "brigadeiro-gourmet",
    name: "Brigadeiro Gourmet",
    description:
      "Brigadeiro cremoso de castanha de caju com cacau 50%, rolado em granulado belga. Sem lactose, sem ovo. A versão vegana do mais brasileiro dos doces — sem abrir mão de nada.",
    category: "docinho",
    gramatura_g: 22,
    price_site: 6.5,
    price_ifood: 8.5,
    attributes: ["sem-lactose", "vegano"],
    tags: ["favoritos", "presente"],
    photo: {
      url: "/produtos/brownie-brigadeiro.png",
      alt: "Brigadeiro gourmet com granulado belga",
    },
    photoSecondary: {
      url: "/produtos/bombom-coco.png",
      alt: "Brigadeiros em caixa de presente",
    },
    active: true,
    stock: 4,
    lowStockThreshold: 5,
    ifoodRating: 4.9,
    ifoodOrderCount: 120,
    serves: 1,
    contains: ["castanha-de-caju", "cacau"],
    freezable: false,
    availableForPreorder: false,
  },
  {
    id: "12",
    slug: "bolo-no-pote-cenoura",
    name: "Bolo no Pote — Cenoura com Brigadeiro",
    description:
      "Massa úmida de cenoura em camadas intercaladas com brigadeiro de castanha de caju. A combinação favorita em formato individual — sem precisar dividir.",
    category: "bolo-no-pote",
    gramatura_g: 230,
    price_site: 17.9,
    price_ifood: 23.3,
    attributes: ["sem-lactose", "vegano"],
    tags: ["afetivos"],
    photo: {
      url: "/produtos/bolo-cenoura-brigadeiro-2.png",
      alt: "Bolo no pote de cenoura com brigadeiro visto de cima",
    },
    photoSecondary: {
      url: "/produtos/bolo-cenoura-calda.png",
      alt: "Corte revelando camadas alternadas de cenoura e brigadeiro",
    },
    active: true,
    stock: 9,
    lowStockThreshold: 3,
    ifoodRating: 4.8,
    ifoodOrderCount: 200,
    serves: 1,
    contains: ["castanha-de-caju", "cacau"],
    freezable: false,
    availableForPreorder: false,
  },
] as const;
